[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "Thesis"
description = "Optimal portfolio strategies for a large universe of assets"
readme = "README.md"
requires-python = ">=3.8"
authors = [
    { name = "Kiril Ivanov", email = "ivanov.r.kiril@abv.bg" },
]
license = "MIT"
dependencies = [
    numpy>=2.4,
    pandas>=3.0,
    scipy>=1.17,
    scikit-learn>=1.8,
    matplotlib>=3.10,
    seaborn>=0.13,   
    nonlinshrink>=0.7,
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]